# Generated by Django 3.2.1 on 2021-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albam',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'worst'), (2, 'bad'), (3, 'not bad'), (4, 'good'), (5, 'Excellent!')]),
        ),
    ]
