# Generated by Django 3.2.1 on 2021-05-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_albam_num_stars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='albam',
            table='Albam',
        ),
    ]
