# Generated by Django 3.2.1 on 2021-05-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_albam_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='albam',
            table=None,
        ),
    ]
